name: global_ops
description: "Global Operational app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

workspace:
  - layer/cache
  - layer/core
  - layer/design_system
  - layer/error_reporter
  - layer/firebase
  - layer/log_reporter
  - layer/module_injector
  - layer/remote
  - layer/tracking
  - layer/use_case

dependencies:
  cache:
    path: layer/cache
  collection: any
  core:
    path: layer/core
  cupertino_icons: ^1.0.8
  design_system:
    path: layer/design_system
  equatable: any
  error_reporter:
    path: layer/error_reporter
  firebase:
    path: layer/firebase
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  geolocator: ^14.0.2
  go_router: ^16.0.0
  image: ^4.5.4
  intl: ^0.20.2
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  log_reporter:
    path: layer/log_reporter
  meta: any
  module_injector:
    path: layer/module_injector
  path: ^1.9.1
  permission_handler: ^12.0.1
  remote:
    path: layer/remote
  synchronized: ^3.4.0
  tracking:
    path: layer/tracking
  use_case:
    path: layer/use_case
  vector_math: ^2.1.4

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.6.0
  custom_lint: ^0.7.6
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.10.0
  lint: ^2.8.0
  melos: ^6.3.3
  mocktail: ^1.0.4
  test: ^1.24.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  generate: true