name: core
description: Provides core functionality for the app.
publish_to: 'none'

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
