name: design_system
description: "Provide design system for the app"
publish_to: 'none'

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  adaptive_breakpoints: ^0.1.7
  alchemist: ^0.12.1
  animated_text_kit: ^4.2.3
  auto_animated: ^3.2.0
  carousel_slider: ^5.1.1
  collection: ^1.19.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  extended_image: ^10.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.3
  pin_code_fields: ^8.0.1
  loading_animation_widget: ^1.3.0
  lottie: ^3.3.1
  meta: any
  readmore: ^3.0.0
  recase: ^4.1.0
  shimmer: ^3.0.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.6.0
  flutter_gen_runner: ^5.11.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/map_styles/


flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: true