name: firestore_export_import
description: A command-line application for exporting and importing content to/from Firestore.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.7.0
  get_it: ^8.2.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.5.0
  logger: ^2.6.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
