name: use_case
description: Provides base classes for making use cases for the app
publish_to: 'none'

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  either_dart: ^1.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  meta: any
  module_injector:
    path: ../module_injector

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true