name: firebase
description: Provides all firebase related features for the app.
publish_to: 'none'

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  cloud_firestore: ^5.6.11
  cloud_functions: ^5.6.1
  core:
    path: ../core
  equatable: ^2.0.7
  firebase_analytics: ^11.5.2
  firebase_app_check: ^0.3.2+9
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_crashlytics: ^4.3.9
  firebase_remote_config: ^5.4.7
  firebase_storage: ^12.4.9
  flutter:
    sdk: flutter
  geoflutterfire_plus: ^0.0.32
  module_injector:
    path: ../module_injector
  path_provider: ^2.1.5

dev_dependencies:
  fake_cloud_firestore: ^3.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
