name: tracking
description: Provides support for analytic event reporting for the app
publish_to: 'none'

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  firebase:
    path: ../firebase
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  module_injector:
    path: ../module_injector
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.6.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.10.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
