name: Analyze and test layer module

on:
  workflow_call:
    inputs:
      module_path:
        type: string
        required: true
      has_build_runner:
        type: string
        required: true
    secrets:
      FIREBASE_OPTIONS_BASE64:
        required: true
      APP_CHECK_TOKEN_BASE64:
        required: true

env:
  FLUTTER_VERSION: 3.32.2

jobs:
  analyze-module:
    name: Format, Analyze, and Test module
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.module_path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup the flutter environment
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: stable
          cache: true

      - name: Decode Firebase Options
        run: |
          echo "${{ secrets.FIREBASE_OPTIONS_BASE64 }}" | base64 --decode > ${{ github.workspace }}/layer/firebase/lib/src/firebase_options.dart

      - name: Decode App Check Token
        run: |
          echo "${{ secrets.APP_CHECK_TOKEN_BASE64 }}" | base64 --decode > ${{ github.workspace }}/layer/firebase/lib/src/app_check/token.dart

      - name: Get dart dependencies
        run: flutter pub get

      - name: Format the Dart code
        run: dart format . --set-exit-if-changed

      - name: Run code generators
        if: inputs.has_build_runner == 'true'
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Get dart dependencies
        if: inputs.has_build_runner == 'false'
        run: flutter pub get

      - name: Statically analyze the Dart code
        run: flutter analyze

      - name: Run unit tests
        run: flutter test --exclude-tags golden --coverage --machine > test-results.json  --no-pub

      - name: Generate test report
        uses: dorny/test-reporter@v1.9.1
        if: always()
        with:
          name: Test Results
          path: test-results.json
          reporter: flutter-json
          working-directory: ${{ inputs.module_path }}
          token: ${{ secrets.GITHUB_TOKEN }}