name: Validate code quality of app

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '*-review'
      - '*-prod'
      - '*-prod-storybook'

permissions: write-all

jobs:
  code_quality_validation:
    uses: ./.github/workflows/_app_static_analyze_with_test.yaml
    secrets:
      FIREBASE_OPTIONS_BASE64: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}
      APP_CHECK_TOKEN_BASE64: ${{ secrets.APP_CHECK_TOKEN_BASE64 }}