name: Cache layer code quality validation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '*-review'
      - '*-prod'
      - '*-prod-storybook'
    paths:
      - 'layer/cache/**'
      - '.github/workflows/layer_cache_code_quality_validation.yaml'

permissions:
  checks: write

jobs:
  layer_cache_code_quality_validation:
    name: Format, Analyze, and Test module
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./layer/cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dart environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_SDK_VERSION }}

      - name: Setup the flutter environment
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: stable
          cache: true

      - name: Decode Firebase Options
        run: |
          echo "${{ secrets.FIREBASE_OPTIONS_BASE64 }}" | base64 --decode > ../firebase/lib/src/firebase_options.dart
        env:
          FIREBASE_OPTIONS_BASE64: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}

      - name: Decode App Check Token
        run: |
          echo "${{ secrets.APP_CHECK_TOKEN_BASE64 }}" | base64 --decode > ../firebase/lib/src/app_check/token.dart
        env:
          FIREBASE_OPTIONS_BASE64: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}

      - name: Get dart dependencies
        run: flutter pub get

      - name: Format the Dart code
        run: dart format . --set-exit-if-changed

      - name: Statically analyze the Dart code
        run: flutter analyze

      - name: Install SQLite
        run: sudo apt-get install -y sqlite3 libsqlite3-dev

      - name: Run unit tests
        run: flutter test --exclude-tags golden --coverage --machine > test-results.json  --no-pub

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: test-results.json
          reporter: flutter-json
          working-directory: ./layer/cache
